# Scikit Learn Basics

In [17]:
# Lifecycle
# Getting data ready
# Choosing ML model
# Fit Model
# Evaluate Model
# Improve the model
# Save Model
# Summary

In [3]:
import pandas as pd

In [21]:
## Getting Data Ready

In [4]:
heart_disease = pd.read_csv("Heart Disease UCI.csv")

In [5]:
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,40,1,3,152,223,0,0,181,0,0.0,0,0,2,1
293,39,1,3,118,219,0,0,140,0,1.2,1,0,2,1
294,35,1,3,120,198,0,0,130,1,1.6,1,0,2,1
295,35,0,3,138,183,0,0,182,0,1.4,0,0,0,0
296,35,1,3,126,282,0,2,156,1,0.0,0,0,2,1

In [6]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0

In [12]:
# Create X
X = heart_disease.drop('condition', axis=1)
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,40,1,3,152,223,0,0,181,0,0.0,0,0,2
293,39,1,3,118,219,0,0,140,0,1.2,1,0,2
294,35,1,3,120,198,0,0,130,1,1.6,1,0,2
295,35,0,3,138,183,0,0,182,0,1.4,0,0,0
296,35,1,3,126,282,0,2,156,1,0.0,0,0,2

In [13]:
# Create Y
Y = heart_disease['condition']
Y

0      0
1      0
2      0
3      1
4      0
      ..
292    1
293    1
294    1
295    0
296    1
Name: condition, Length: 297, dtype: int64

In [22]:
## Choosing ML model

In [20]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [23]:
## Fit The Model

In [25]:
from sklearn.model_selection import train_test_split
X_test, X_train, Y_test, Y_train = train_test_split(X, Y , test_size=0.3)

In [27]:
clf.fit(X_train, Y_train)

RandomForestClassifier()

In [28]:
## Evaluate the model

In [29]:
predicted_y = clf.predict(X_test)
predicted_y

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0])

In [30]:
clf.score(X_train, Y_train)

1.0

In [31]:
clf.score(X_test, Y_test)

0.7922705314009661

In [32]:
## Improve the model

In [38]:
for i in range(10,200,10):
    print(f'Running model with {i} estimators')
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, Y_train)
    print(f'Accuracy is : {clf.score(X_test, Y_test)}')

Running model with 10 estimators
Accuracy is : 0.782608695652174
Running model with 20 estimators
Accuracy is : 0.8019323671497585
Running model with 30 estimators
Accuracy is : 0.8019323671497585
Running model with 40 estimators
Accuracy is : 0.8019323671497585
Running model with 50 estimators
Accuracy is : 0.7922705314009661
Running model with 60 estimators
Accuracy is : 0.7971014492753623
Running model with 70 estimators
Accuracy is : 0.7922705314009661
Running model with 80 estimators
Accuracy is : 0.8115942028985508
Running model with 90 estimators
Accuracy is : 0.8019323671497585
Running model with 100 estimators
Accuracy is : 0.8164251207729468
Running model with 110 estimators
Accuracy is : 0.8019323671497585
Running model with 120 estimators
Accuracy is : 0.7922705314009661
Running model with 130 estimators
Accuracy is : 0.7971014492753623
Running model with 140 estimators
Accuracy is : 0.7971014492753623
Running model with 150 estimators
Accuracy is : 0.7874396135265701
Running model with 160 estimators
Accuracy is : 0.8067632850241546
Running model with 170 estimators
Accuracy is : 0.7971014492753623
Running model with 180 estimators
Accuracy is : 0.7874396135265701
Running model with 190 estimators
Accuracy is : 0.8019323671497585

In [40]:
## Save Model

In [41]:
import pickle

In [42]:
pickle.dump(clf,open('heart_disease.pkl','wb'))

In [43]:
load_model = pickle.load(open('heart_disease.pkl','rb'))
load_model.score(X_test, Y_test)

0.8019323671497585

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
heart_disease = pd.read_csv('Heart Disease UCI.csv')

In [4]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0

In [5]:
X = heart_disease.drop('condition', axis=1)
Y = heart_disease['condition']

In [8]:
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0

In [9]:
Y.head()

0    0
1    0
2    0
3    1
4    0
Name: condition, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_test, X_train, Y_test, Y_train = train_test_split(X, Y , test_size=0.25)

In [13]:
X_train.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
dtype: object